set /a ID=%random% %%40
set list=A B

IF "%ID%"=="0" set list=point childlike cut unusual aware mix move unite embarrassed sable simple jolly suggest fearful robin plug maid park harbor grey knock cloth destroy rock peel practise scarf accept bikes amuck mellow unaccountable support literate plant aberrant
IF "%ID%"=="1" set list=unite mushy acid mountain homeless healthy arithmetic burly organic crazy pushy trap carve plug second wriggle team taboo rustic burn attend spell protest rake spot route lacking energetic addition powder staking truculent parallel nine ruthless noiseless
IF "%ID%"=="2" set list=imminent bright advise rely wood trashy drown new want prepare increase battle amused poison glue provide dad soggy curvy didactic middle annoying fearless rings vegetable snails notebook clear handle introduce action trains drop worried redundant available
IF "%ID%"=="3" set list=ray work star carry mist solid sweltering tired clip plastic panicky whip hammer quilt filthy book bashful maid delirious angle sprout type malicious exultant stain birthday needle notebook seashore free maniacal clam circle apparel obscene school
IF "%ID%"=="4" set list=breezy bridge square party ratty waste coach sad blind press friends mice believe eggs fluttering long-term sheep gaudy inject wish alcoholic ragged trap things waiting reject truthful dam knife spark abrupt rose roll aunt pollution bedroom
IF "%ID%"=="5" set list=cooing desert screw delight lopsided limit moor crayon move overwrought account future tank zonked aromatic therapeutic coach skin jelly drab curve pointless flimsy closed unequaled kiss calculate knot angry dusty deliver hissing describe two greet tiny
IF "%ID%"=="6" set list=treatment fool acceptable snore super heat salt righteous difficult accurate room humdrum stay lunchroom zoo disagreeable invincible box level trouble rot hollow milky cut mellow gainful legs curved innate wood crazy honorable clammy belligerent dress x-ray
IF "%ID%"=="7" set list=avoid miniature teeny-tiny lamp rural dust mine allow turn toad wait worthless suspend tail rejoice needle familiar destruction frightening cheerful elite scream thought pancake ban stamp mice cowardly rain abject boast wealthy trains quiver heat prepare
IF "%ID%"=="8" set list=thundering follow serious kiss floor big squash debt rigid picayune tub impossible person tight stop existence wanting redundant milk troubled volcano horn cruel lock bat flagrant sprout prepare laugh crayon dynamic itchy beneficial flashy trite ambiguous
IF "%ID%"=="9" set list=chubby balance wonder physical auspicious joke fast bake scary aberrant thin train roomy thick harsh consist horses escape bottle bleach historical glue doctor bless pig grandfather turn fog letter match suck subtract heal locket cough wacky
IF "%ID%"=="10" set list=history supreme desire wrestle present dare wine loaf snatch easy obtain bulb charming bow jellyfish form noxious part crabby development upset woebegone fresh glistening abrasive kittens coordinated amuse deeply stem snail water perpetual year precede even
IF "%ID%"=="11" set list=white army treatment abandoned marble muscle night level ocean design silent cagey sky unruly remember fuel hunt key name strip unequal decisive group wretched soft run detail queen stitch wave wail minute snobbish troubled strap chemical
IF "%ID%"=="12" set list=fall tender obey cave cars hard-to-find risk ball discover lowly lean teeth own shade taste complete insidious low didactic tangy savory new quicksand pan undesirable sky placid trick old-fashioned sink charming curve close far notebook wing
IF "%ID%"=="13" set list=lopsided deer metal form invent breath beg trace spoil sea trouble actor knowledgeable form bedroom measure rhetorical square cart calculating disturbed equal bath diligent wooden naughty want mom dull big frantic strip happy dusty stimulating messy
IF "%ID%"=="14" set list=ladybug grandmother poor heat help ocean underwear warlike bucket new enthusiastic bubble hurried unwieldy squeeze thoughtless third irritate energetic discovery rely hug noisy attract wealthy irritating selfish waves cobweb nest fade kindly act cut parched insidious
IF "%ID%"=="15" set list=curve pine abnormal rejoice experience finger melted neighborly drunk grandfather jumpy desire resolute brush untidy wasteful trouble jail cup gold volleyball berry moaning clumsy deserve tiny punishment disapprove light private brash kind fierce delicate remember obedient
IF "%ID%"=="16" set list=trip combative caption subdued snake compete instruct babies mellow murder live copper cover spot whip womanly pumped lovely advise crib expert toothpaste trite excuse earthy fancy exist rain imagine raise hat idiotic legs cap order title
IF "%ID%"=="17" set list=poison bloody debonair wretched scorch badge decorous delicious admire squealing crooked liquid female kind harbor cheap value wary maddening psychotic zesty eggs spy eager wipe glamorous chess delightful magnificent call attach shy deeply huge fear dark
IF "%ID%"=="18" set list=grip equal dear structure blind rat stretch squalid vase brake fog crime stamp thread ill-informed dogs camp stir lighten breezy quirky disgusting rule bent test top necessary view books arithmetic arrest one boiling fixed things hate
IF "%ID%"=="19" set list=uppity synonymous tumble puffy cross jealous avoid spade mark enthusiastic gaze promise books teeny half question subtract cattle mute curious jelly excite imminent quaint busy drag measure approval admire fry tent skirt sneaky shut adaptable stimulating
IF "%ID%"=="20" set list=edge disgusting melodic yoke future voracious excite skillful shake bead punch step vest waves greedy ring scold knock nerve red dinosaurs refuse argument decisive soggy egg stretch well-to-do hesitant draconian skin nation march even hope hour
IF "%ID%"=="21" set list=house please throne dark ill-fated pen escape join eye potato interesting dizzy play laughable cream trace fortunate cover trouble sponge help merciful relax lean army motionless stir basket lyrical destruction observation second bomb slip zoo reason
IF "%ID%"=="22" set list=plate imperfect found various neighborly divide boast tire racial end weather jaded loaf far-flung reduce plot selfish sedate check historical relation spiritual helpless tired workable burn raspy itchy kindhearted obese stingy domineering possible guitar bolt pretend
IF "%ID%"=="23" set list=trip neck air observation undress page callous heavy sponge chance cute tank hover train scare hapless quirky pass cautious imperfect trade nimble bawdy look obscene little regret shut nest snail recondite aromatic bite-sized grumpy knife aware
IF "%ID%"=="24" set list=fearless learn raise cook tempt sound back versed railway enchanting synonymous helpful business ink vagabond harass cherry great alert material swing coordinated interrupt fixed nervous silent advise berry wail boorish place envious recognise hard-to-find wool lyrical
IF "%ID%"=="25" set list=super listen annoying leather frame heavenly ice quarrelsome cough stew window acceptable instruct rebel rude nebulous arithmetic rural work enjoy nice smell pricey dime dangerous lumpy decay basketball utopian mute thumb camp match exclusive fretful discussion
IF "%ID%"=="26" set list=ladybug whisper damaging rinse desire famous theory toad glib event fact nod quill preach sea frail eatable fast difficult heap orange little paste silent exotic wacky notebook wandering crayon even stew back sick noise happy lavish
IF "%ID%"=="27" set list=incredible kick comb noisy club umbrella thinkable wobble plan impulse direction purpose homely identify second-hand amount wait illustrious bottle slippery field optimal toes clean evasive abhorrent kiss discreet offbeat protective fortunate film ugly consider onerous rose
IF "%ID%"=="28" set list=brick sparkling blot woebegone squash depend tall instrument floor naughty blink mailbox tranquil snakes dreary puffy skin utopian recess drop blue-eyed jazzy doubtful pat look sharp wonderful nest spark calm tricky curtain nation park stingy rake
IF "%ID%"=="29" set list=need dapper iron library happen exercise representative coordinated mask destroy society challenge van watery sheep playground cake natural plot known driving transport tub step cough possess rose unkempt polish eatable flood light learned complete play marble
IF "%ID%"=="30" set list=fanatical letters pass envious melodic side awful sigh questionable sheet new bait drink dull current nerve psychedelic attract skirt erratic nest red tired circle cheat exist manage ruin sign painful bewildered drawer examine airplane pop ruddy
IF "%ID%"=="31" set list=solid faithful appreciate downtown x-ray stop safe near busy drain majestic shiver attend yam picayune dangerous excellent stitch husky account decisive rest cause cellar donkey false wiry overjoyed aggressive ancient riddle chickens suspend mask channel creator
IF "%ID%"=="32" set list=long carriage next spill voiceless open spiritual different meat last flowery desire angry living bucket design curtain grotesque club drain rose debt unlock position stale agreeable precious action puzzling uninterested murky exchange geese grease bleach weak
IF "%ID%"=="33" set list=heartbreaking tumble snake use possible lovely arrange train wicked flowery box splendid mother roomy exotic scold skirt request odd tire boundless important poor pancake handy debonair tick few unable cub welcome purring history oafish refuse opposite
IF "%ID%"=="34" set list=use vegetable decision invent sail mess up employ thoughtful motionless icy whip low six rigid mourn ring appliance painstaking lowly shape probable bomb celery hammer smell shrill knot consider direful grateful agreeable damaged squeal rush hook car
IF "%ID%"=="35" set list=thing unruly pump accept afford calculate short signal store sea workable weary cub smart heavy support oafish suck enormous base locket available tart eminent aboriginal peck oceanic dust boundary certain selective ignorant guttural abundant broad crush
IF "%ID%"=="36" set list=fearful sign young parcel mourn shade structure design annoyed zonked pathetic gorgeous milk part day second-hand beds surprise raspy protective bumpy alleged box cool picayune subsequent sedate horrible chance untidy lie panoramic reaction quick answer heavy
IF "%ID%"=="37" set list=dolls statement reply bow burly oval fluttering cluttered abundant expand handle badge babies charge screw risk icky cheap show private rough tray man sock forgetful admit lovely touch unfasten frantic challenge sea cemetery oatmeal matter analyse
IF "%ID%"=="38" set list=homeless puzzled sturdy explode bait secretary peel found accept prepare honorable frogs better depend advise encourage ill store education fear zoo blush decay early reach handsomely dress angry sneaky injure warlike bedroom fire analyse end eight
IF "%ID%"=="39" set list=vague grate warn division jewel draconian brick nebulous heat bolt excited partner fit secretary puzzling dry motion tent maddening chop womanly milky chance high place wax heat scintillating whip time daily jar snails hop overwrought many

# Every 5 seconds, open up a new tab with the word selected from the list.
(for %%a in (%list%) do (
	start microsoft-edge:http://www.bing.com/search?q=%%a
	timeout 5
))

# Pull up a tab for the Daily Points
start microsoft-edge:https://account.microsoft.com/rewards/dashboard?refd=www.bing.com
