set /a ID=%random% %%40
set list=A B

IF "%ID%"=="0" set list=soprano force customer edition progressive grace hold desert intelligence debut claim representative restrict secular stall volcano short deficiency hallway supplementary woman eye gaffe theme bundle gallery character piece integration stubborn veil gun fleet section cable compartment conceive comfort
IF "%ID%"=="1" set list=statuesque fall remind stop momentous march tremble groan use abandoned beautiful behavior wash hot mammoth balance sedate cave satisfy type table zinc electric beef ambiguous striped fuzzy hateful animated care stamp long present tie harbor present labored achiever
IF "%ID%"=="2" set list=imagine chubby place play melt credit bathe imperfect porter wash spotless poor repeat mind shade prick false mark spark argue fog analyse fly miscreant questionable closed callous zinc purpose rings muscle shoes enter energetic safe meddle squash detect
IF "%ID%"=="3" set list=delicate rough inject rotten library stop fact auspicious bored vague important equable unusual rampant rightful march abnormal aloof clover malicious cloth communicate rapid awful quill courageous sore afraid hideous horses reward disastrous delay clear roll innate committee stormy
IF "%ID%"=="4" set list=hypnotic rainy tasteless yoke gratis cause sheet transport elegant twig alive rhyme highfalutin moan giants loud high offbeat hydrant scandalous abiding yarn face tramp thing unfasten stupid grieving square sick fear bump serve step sharp loss wish economic
IF "%ID%"=="5" set list=versed sort woebegone jewel wilderness accidental grip slim mint announce explain devilish cultured include bare yummy drop lucky breezy dashing waves afterthought month crime sticks marble wood abnormal delicate humor touch comparison attack irritate few third quicksand trace
IF "%ID%"=="6" set list=type drip expensive vein field trite sordid birthday train cap spell appliance scale drunk press challenge resonant grease fair pleasant thought throat unite toes bit didactic wealth servant lush alive quixotic false provide mountain squeeze disillusioned use creator
IF "%ID%"=="7" set list=wind sassy strip country repulsive languid overrated heat correct opposite home hook match interfere kick sheep obtainable whispering wait branch hum twist mysterious shocking dead abrasive jog bustling frame endurable soak lip seat quickest station romantic look deceive
IF "%ID%"=="8" set list=play flow alarm carpenter trouble colour produce cure elfin camera kill obedient brawny lighten lopsided fuzzy square pump use deadpan string foregoing program trail impress attach annoying robust acidic alert request grotesque snore spell ajar marked wheel puncture
IF "%ID%"=="9" set list=square oafish unbiased tumble coach polish inquisitive notebook stereotyped low choke fowl flat hellish smile faint replace full snatch apparatus rambunctious bulb stranger mere passenger icicle spiritual cheerful married dinosaurs amuck white colossal punch glove boil yielding lock
IF "%ID%"=="10" set list=meeting shame hard-to-find apparel plane curvy vagabond panoramic silk excite mysterious fabulous groan boundless color jagged waves riddle holistic domineering chunky bang bored grass value short macho plausible natural water cakes murky pumped guard overconfident coach hope attack
IF "%ID%"=="11" set list=label red join tense distinct filthy axiomatic surround death box flood hapless circle girls visitor giants known drop farm song bump spicy wrathful doubtful desire shivering abundant unite satisfy aromatic dynamic unhealthy event superficial bizarre ray torpid cemetery
IF "%ID%"=="12" set list=vase alert tightfisted wide worried cloistered full air channel pig educated doctor drown plastic upset first amusing enchanted accept sink honey handle defiant aback smoke sound somber clear discussion scare attraction sparkle chalk note quixotic pen mundane willing
IF "%ID%"=="13" set list=unfasten cynical aromatic table start cheerful unit lame science addicted zonked illustrious whirl spark smash try vanish slim rob amazing camp taboo wide-eyed moaning thrill exclusive bee knife cattle squirrel boast unarmed knowledge snobbish shelf replace aloof well-off
IF "%ID%"=="14" set list=unknown taste son thank cover half dispensable collect honorable chin majestic deadpan steadfast real drain company dazzling quilt flesh pie join clumsy ablaze aboriginal twist hobbies bushes extra-small victorious aloof crayon aware command stranger spiteful camp exultant doubt
IF "%ID%"=="15" set list=ill-informed profit interfere warlike eatable nation elfin sail egg conscious bait wild treatment prick ad hoc sign grieving discovery fasten post earthquake month morning waste curly massive ceaseless brass money protect program cakes sweater allow known agreeable crowded scorch
IF "%ID%"=="16" set list=elated land overjoyed pedal fog hulking spectacular clam reason important drop card examine summer windy shirt giants nervous curl foolish mature worthless bomb periodic scrawny stay bow deserted wistful phone suit slave serious wave chickens line straight feeling
IF "%ID%"=="17" set list=desert sudden bomb jobless back grandfather observant living wealth weight shop fuel driving view telephone automatic strange food few letters green tense capricious learned babies juicy happy quarter square airplane honorable obscene protect connect transport donkey quartz lamp
IF "%ID%"=="18" set list=discover slip questionable decision sail breath loving smoke sound eggnog unbecoming cross previous behave boat miniature dust fax enthusiastic colorful weary company amusement cats tiger astonishing present homeless possessive unwritten hollow alert spiritual ants curve suit quickest writing
IF "%ID%"=="19" set list=shock chubby honey filthy strange inject ragged one spark eight sisters fold expansion adorable letters ruddy gainful suck guide twig plucky wool lively moan spiffy frantic famous fetch nervous gabby material veil cheat rough fallacious future war flag
IF "%ID%"=="20" set list=stretch street whimsical uppity pinch burst box crime lunch staking holistic acrid amazing disagree permissible spectacular nose grotesque wealthy marvelous cheerful horses jewel work lackadaisical table occur tree arm clear zoom appear windy giants stroke order reply toy
IF "%ID%"=="21" set list=branch dispensable welcome bath unadvised certain enthusiastic kill talk space chemical pail square skate flesh expert admit lowly dance gusty elite plantation pointless third disappear productive early large busy melodic wood day save grade like love open undesirable
IF "%ID%"=="22" set list=frame wreck flame plough rabbits hissing deep wail expensive sigh shaky nondescript present cap marble jump frantic next homely crabby verdant kick slip kind can soak hospitable rhythm courageous join idiotic puzzled electric juvenile penitent pigs advise offend
IF "%ID%"=="23" set list=flat rare crack debt addition lunchroom flagrant obedient jellyfish glib release spiffy cynical effect smash push pocket dashing excite snatch protect lame white war memory direful abnormal false rough capricious sparkle clumsy proud eyes cruel satisfy ordinary cap
IF "%ID%"=="24" set list=paltry memorise hands verse adjoining strong raspy earthquake arrest abnormal tight hose van exclusive excellent trap friends surprise fire respect entertain can punish straight closed instrument worry obtainable omniscient sneeze add pest tasteless divide dry stream level toothsome
IF "%ID%"=="25" set list=brave room aboriginal object advertisement remarkable poison absorbed poke daughter spiteful disastrous apparatus crooked salty threatening idiotic glib scientific tender race unable zebra push lethal mundane floor weight offer loutish slip hope level wacky boot bucket note dizzy
IF "%ID%"=="26" set list=walk actor protest tour expensive friendly hair ritzy babies dime deep competition finger servant scarce gamy shame mine rice incompetent cold strengthen extend record rose probable brick tempt horses ask concentrate stitch divide volleyball change fog lowly pig
IF "%ID%"=="27" set list=root play handsome comfortable defective light plausible boring impossible choke try shrill last cheer experience tiger increase scissors thinkable thoughtful sip scene acoustic low spill sin creator knock known dance strip pan press blue bright rain hammer disarm
IF "%ID%"=="28" set list=safe scale flag delightful difficult jittery bless orange swim serve observation channel bone defeated standing store necessary tour absurd work visitor shirt quirky man desire aquatic furry clip offer confess talk zephyr second-hand adorable metal copy force interesting
IF "%ID%"=="29" set list=rest cactus mere lovely pipe stomach wandering imaginary hour coach holiday towering brief perpetual rampant scrape week shave alluring scientific authority kick profit numberless fuzzy jelly instruct analyse daffy jump trust equable racial pets panoramic clean marry youthful
IF "%ID%"=="30" set list=barbarous hushed mountain sigh farm shrill black church harass animal direction delight bitter elegant phobic enjoy vest quickest drag dispensable divide extend consider snow linen solid torpid play simplistic stream jumbled stage smoke sign table dime talk silver
IF "%ID%"=="31" set list=flap pretty desire birds agree disappear tacky icicle tap kiss aboard rule outstanding sweltering rhetorical elastic hose abrupt puzzling change useful ad hoc crown plants wheel note motionless close flower signal fill sheep building sore gusty delightful annoy productive
IF "%ID%"=="32" set list=plain chop splendid possessive bridge change aback kneel possible trade fade things three provide wren wax nest snake puncture trip insect ray open oranges frame mighty juice volleyball kittens quartz living vengeful jump injure fluffy stare same cars
IF "%ID%"=="33" set list=jar worm unlock frame insurance clammy versed five memorise chief plug ruthless fork authority thunder wooden better lush place exercise reminiscent second mass remove defiant learned squeeze sweltering open theory ten level abhorrent jellyfish impossible huge descriptive system
IF "%ID%"=="34" set list=abandoned knock start pedal pump friend cold aromatic twist sophisticated violet dramatic handle easy rod stove camp cars territory paltry jolly cake examine tickle tiresome trashy carry substance hook fearless cable saw neighborly hour freezing internal wave sleet
IF "%ID%"=="35" set list=square street plot son price scissors ordinary comb sisters seemly position foregoing balance light animal account surprise delirious small therapeutic walk gullible reward tremendous aboard copper bad habitual teeny motion lace grain box icicle lumpy imperfect puzzled moon
IF "%ID%"=="36" set list=rich river cause permit jelly apparatus enchanted bat lip naive obtainable exultant versed animated disastrous wrench branch announce sprout offer thinkable bikes hover land offbeat need berserk program jeans cattle chief discreet stiff mellow voice fresh nutritious normal
IF "%ID%"=="37" set list=push squeeze coil mountainous heartbreaking wriggle observe aboard consider boil sand decorous crayon long idea macabre steer ashamed skip natural psychedelic crow bright secret present scene frightening heavy ring secretary lonely twist clear alcoholic flippant comfortable responsible seashore
IF "%ID%"=="38" set list=worried telephone waves example sore coat towering silk hydrant present steadfast painful nonchalant support chivalrous listen inexpensive earthquake unwieldy kind calculate follow doctor jelly puzzled tranquil utopian fact heat note full juicy include stir dazzling preach ill succinct
IF "%ID%"=="39" set list=boat zesty line celery satisfy bathe border understood behave puzzled brown pen question reason guarded spiky cat squeak power plant design frail absorbed accessible stitch serve ground war yellow thumb bake turn name lumpy work icicle settle rightful

# Every 5 seconds, open up a new tab with the word selected from the list.
(for %%a in (%list%) do (
	start microsoft-edge:http://www.bing.com/search?q=%%a
	timeout 6
))

# Pull up a tab for the Daily Points
start microsoft-edge:https://account.microsoft.com/rewards/dashboard?refd=www.bing.com
